libraryapp/urls.py
from django.conf.urls import url
from .views import *
from django.urls import path
from . import views

app_name = 'libraryapp'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('about/', AboutView.as_view(), name='about'),
    path('services/', ServiceView.as_view(), name='service'),
    path('contact/', ContactView.as_view(), name='contact'),
    path('login/', LoginForm.as_view(), name='login'),
    path('admin/home/', AdminHome.as_view(), name='adminhome'),
    path('admin/book/list/', BookListView.as_view(), name='booklist'),
    path('admin/book/create/', BookCreateView.as_view(), name='bookcreate'),
    path('admin/book/update/<int:pk>/',
         BooKUpdateView.as_view(), name='bookupdate'),
    path('admin/book/delete/<int:pk>/',
         BookdeleteView.as_view(), name='bookdelete'),
    path('admin/student/list', StudentListView.as_view(), name='studentlist'),
    path('admin/student/create', StudentCreateView.as_view(), name='studentcreate'),
    path('admin/student/update<int:pk>', StudentUpdateView.as_view(), name='studentupdate'),
    path('admin/student/delete/<int:pk>/',
         StudentDeleteView.as_view(), name='studentdelete'),
    path('admin/student/issue/',views.IssueBookView,name = 'issue'),





]

libraryproject/urls.py
from django.conf.urls import url
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    path('', include('libraryapp.urls')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/libraniantemplates/libranianabout.html
{% extends 'libraniantemplates/libranianbase.html' %}
{% load static %}
<title>{% block title %}about{% endblock %}</title>

<body>
{% block content %}
<div class="about-w3-agile" id="about">
		<div class="container">
			<div class="wthree_about_grids">
				<div class="col-md-6 wthree_about_grid_left">
					<h3>About us</h3>
							<p>Fusce semper, nibh eu sollicitudin imperdiet, dolor magna vestibulum mi, 
								vel tincidunt augue ipsum nec erat. Vestibulum congue leo elementum 
								ullamcorper commodo. Class aptent taciti sociosqu ad litora torquent 
								per conubia nostra, per inceptos himenaeos.</p>
								<a href="#" data-toggle="modal" data-target="#myModal">Read More</a>
				</div>
				<div id="myModal" class="modal fade" role="dialog">
					<div class="modal-dialog">
						<div class="modal-content">
						  <div class="modal-header">
							<button type="button" class="close" data-dismiss="modal">&times;</button>
							<h4 class="modal-title">Modal Header</h4>
						  </div>
						  <div class="modal-body">
							<p>Nam tincidunt leo nec molestie accumsan. Fusce iaculis sit amet tellus vel ultrices. Phasellus in tellus ut orci accumsan facilisis eget in ante. Aliquam laoreet finibus augue non pharetra. Nullam tincidunt ex quis massa auctor, quis auctor erat semper. Morbi a justo auctor, semper mi viverra, lacinia libero. Praesent sodales augue tristique tellus eleifend, eu placerat eros hendrerit. Cras imperdiet lorem nec magna congue, blandit auctor arcu posuere. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.</p>
						  </div>
						  <div class="modal-footer">
							<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
						  </div>
						</div>
					</div>
				</div>

				<div class="col-md-6 wthree_about_grid_right">
					<img src="{% static 'images/11.jpg' %}" alt=" " class="img-responsive" />
				</div>
				<div class="clearfix"> </div>
			</div>
		</div>
	</div>
{% endblock %}
</body>

templates/libraniantemplates/libranianbase.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
<title>
    {% block title %}{% endblock %}
 </title>

<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
<!-- css --> 
<link href="{% static 'css/bootstrap.css' %}" rel="stylesheet" type="text/css" media="all" />
<link href="{% static 'css/popup-box.css' %}" rel="stylesheet" type="text/css" media="all" />

<link rel="stylesheet" href="{% static 'css/style.css' %}" type="text/css" media="all" />
<link rel="stylesheet" 	href="{% static 'css/chocolat.css' %}" type="text/css" media="all">
<!--// css -->
<!-- font -->
<link href='//fonts.googleapis.com/css?family=Josefin+Sans:400,100,100italic,300,300italic,400italic,600,600italic,700,700italic' rel='stylesheet' type='text/css'>
<link href='//fonts.googleapis.com/css?family=Open+Sans:400,300,300italic,400italic,600,600italic,700,700italic,800,800italic' rel='stylesheet' type='text/css'>
<!-- //font -->
<script src="{% static 'js/jquery-1.11.1.min.js' %}"></script>
<script src="{% static 'js/bootstrap.js' %}"></script>
	<!-- Popup-Box-JavaScript -->
	<script src="js/modernizr.custom.97074.js"></script>
	<script src="js/jquery.chocolat.js"></script>
	<script type="text/javascript">
		$(function() {
			$('.gallery-grids a').Chocolat();
		});
	</script>
	<!-- //Popup-Box-JavaScript -->
	<!-- start-smooth-scrolling -->
			<script type="text/javascript" src="js/move-top.js"></script>
			<script type="text/javascript" src="js/easing.js"></script>
			<script type="text/javascript">
				jQuery(document).ready(function($) {
					$(".scroll").click(function(event){		
					event.preventDefault();
					$('html,body').animate({scrollTop:$(this.hash).offset().top},1000);
				});
			});
			</script>
	<!-- //start-smoth-scrolling -->
		<!-- here stars scrolling icon -->
	<script type="text/javascript">
		$(document).ready(function() {
			/*
				var defaults = {
				containerID: 'toTop', // fading element id
				containerHoverID: 'toTopHover', // fading element hover id
				scrollSpeed: 1200,
				easingType: 'linear' 
				};
			*/
								
			$().UItoTop({ easingType: 'easeOutQuart' });
								
			});
	</script>
	<script src="js/jquery.magnific-popup.js" type="text/javascript"></script>
<script type="text/javascript" src="js/modernizr.custom.53451.js"></script> 
 <script>
						$(document).ready(function() {
						$('.popup-with-zoom-anim').magnificPopup({
							type: 'inline',
							fixedContentPos: false,
							fixedBgPos: true,
							overflowY: 'auto',
							closeBtnInside: true,
							preloader: false,
							midClick: true,
							removalDelay: 300,
							mainClass: 'my-mfp-zoom-in'
						});
																						
						});
</script>	
</head>
<body>
	<div class="header">
		<div class="container">
			<div class="w3l_header_left"> 
				<ul>
					<li><span class="glyphicon glyphicon-earphone" aria-hidden="true"></span>+977 09272828282</li>
					<li><span class="glyphicon glyphicon-envelope" aria-hidden="true"></span><a href="mailto:info@example.com">brand@example.com</a></li>
				</ul>
			</div>
			
			<div class="w3l_header_right">
				<ul>
					<li><a class="book popup-with-zoom-anim button-isi zoomIn animated" data-wow-delay=".5s" href="{% url 'libraryapp:login' %}"><span class="glyphicon glyphicon-user" aria-hidden="true"></span>login</a></li>
				<!-- 	<li><a class="book popup-with-zoom-anim button-isi zoomIn animated" data-wow-delay=".5s" href="#small-dialog2"><span class="glyphicon glyphicon-user" aria-hidden="true"></span>Sign Up</a></li> -->
				</ul>
			</div>
			
			<div class="clearfix"> </div>
			
		</div>
	</div>
	<div class="logo-navigation-w3layouts">
		<div class="container">
		<div class="logo-w3">
			<a href="#"><h1 style="color: black;"><span>Mylibrary</span></h1></a>
		</div>
		<div class="navigation agileits w3layouts">
			<nav class="navbar agileits w3layouts navbar-default">
				<div class="navbar-header agileits w3layouts">
					<button type="button" class="navbar-toggle agileits w3layouts collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false">
						<span class="sr-only agileits w3layouts">Toggle navigation</span>
						<span class="icon-bar agileits w3layouts"></span>
						<span class="icon-bar agileits w3layouts"></span>
						<span class="icon-bar agileits w3layouts"></span>
					</button>
				</div>
				<div class="navbar-collapse agileits w3layouts collapse hover-effect" id="navbar">
					<ul class="agileits w3layouts">
						<!-- {% url 'libraryapp:home' as home %}
  						{% url 'libraryapp:about' as about %}
  						{% url 'libraryapp:services' as personal %} -->
  						{% with url_name=request.resolver_match.url_name %}
						<li><a href="{% url 'libraryapp:home' %}" class="{% if url_name == 'home' %}active{% endif %}">Home</a></li>
						<li><a href="{% url 'libraryapp:about' %}" class="{% if url_name == 'about' %}active{% endif %}">About</a></li>
						<li><a class="{% if url_name == 'service' %}active{% endif %}" href="{% url 'libraryapp:service' %}">Services</a></li>
						<li><a class="{% if url_name == 'contact' %}active{% endif %}" href="{% url 'libraryapp:contact' %}">Contact</a></li>
						{% endwith %}
					</ul>
				</div>
			</nav>
		</div>
		<div class="clearfix"></div>
		</div>
	</div>
{% block content %}
{% endblock %}
<!-- footer -->
<div class="footer-w3l">
		<p> &copy; 2019 Inspire . All Rights Reserved | Design by <a href="http://w3layouts.com">ramthapa</a></p>
</div>

templates/libraniantemplates/libraniancontact.html
{% extends 'libraniantemplates/libranianbase.html' %}
{% load static %}
<title>
	{% block title %}contact_form{% endblock %}
</title>
<body>
{% block content %}
<div class="contact-w3-agileits" id="contact">
		<div class="container">
			<div class="col-md-5 contact-left-w3ls">
				<h3>Contact info</h3>
				<div class="visit">
					<div class="col-md-2 contact-icon-wthree">
						<span class="glyphicon glyphicon-home" aria-hidden="true"></span>
					</div>
					<div class="col-md-10 contact-text-agileinf0">
						<h4>Visit us</h4>
						<h5>Parma Via Modena,BO, Italy</h5>
					</div>
					<div class="clearfix"></div>
				</div>
				<div class="mail">
					<div class="col-md-2 contact-icon-wthree">
						<span class="glyphicon glyphicon-envelope" aria-hidden="true"></span>
					</div>
					<div class="col-md-10 contact-text-agileinf0">
						<h4>Mail us</h4>
						<h5><a href="mailto:info@example.com">info@example.com</a></h5>
					</div>
					<div class="clearfix"></div>
				</div>
				<div class="call">
					<div class="col-md-2 contact-icon-wthree">
						<span class="glyphicon glyphicon-phone" aria-hidden="true"></span>
					</div>
					<div class="col-md-10 contact-text-agileinf0">
						<h4>Call us</h4>
						<h5>+18044261149</h5>
					</div>
					<div class="clearfix"></div>
				</div>
				<div class="visit">
					<div class="col-md-2 contact-icon-wthree">
						<span class="glyphicon glyphicon-time" aria-hidden="true"></span>
					</div>
					<div class="col-md-10 contact-text-agileinf0">
						<h4>Work hours</h4>
						<h5>Mon-Sat 09:00 AM - 05:00PM</h5>
					</div>
					<div class="clearfix"></div>
				</div>
			</div>
			<div class="col-md-7 contact-right-w3l">
				<h3>Leave message</h3>
				<form method="post" action="#">
					{% csrf_token %}
					{{ form.as_p }}
					<button class="btn btn-warning">send messagel</button>
					
				</form>				
			</div>
		<div class="clearfix"></div>
	</div>
</div>
<!-- <form action="#" method="post">
					<input type="text"  class="name" name="name" placeholder="First Name" required="">
					<input type="text"  class="name" name="name" placeholder="Last Name" required="">
					<input type="text"  class="name" name="name" placeholder="Email" required="">
					<input type="text"  class="name" name="name" placeholder="Subject" required="">
					<textarea placeholder="Your Message" required=""></textarea>
					<input type="submit" value="SEND MESSAGE">
				</form> -->
{% endblock %}
</body>

templates/libraniantemplates/libranianhome.html
{% extends 'libraniantemplates/libranianbase.html' %}
{% load static %}
<title>{% block title %}Home{% endblock %}</title>
<body>
{% block content %}

<div class="banner">
		<h3>Education is ornament</h3>
		<h2><span>To </span>learn</h2>
		<h4>our goal is to spread knowlege about education</h4>
		<div class="arrow">
			<a href="#contact" class="scroll"><img src="{% static 'images/arrow.png' %}" alt=" " /></a>
		</div>
</div>

<div class="featured-work">
		<div class="container">
			<h3>Featured work</h3>
			<div class="col-md-6 featured-left">
				<div class="wmuSlider example1 animated wow slideInUp" data-wow-delay=".5s">
					<div class="wmuSliderWrapper">
						<article style="position: absolute; width: 100%; opacity: 0;"> 
							<div class="banner-wrap">
								<img src="{% static 'images/f1.jpg' %}" alt=" " class="img-responsive" />
							</div>
						</article>
						<article style="position: absolute; width: 100%; opacity: 0;"> 
							<div class="banner-wrap">
								<img src="{% static 'images/f2.jpg' %}" alt=" " class="img-responsive" />
							</div>
						</article>
						<article style="position: absolute; width: 100%; opacity: 0;"> 
							<div class="banner-wrap">
								<img src="{% static 'images/f3.jpg' %}" alt=" " class="img-responsive" />
							</div>
						</article>
					</div>
				</div>
			</div>
			<script src="{% static 'js/jquery.wmuSlider.js' %}"></script> 
								<script>
									$('.example1').wmuSlider();         
								</script> 

			<div class="col-md-6 featured-right">
				<h4>Quisque lobortis</h4>
				<p>Nam a leo porta, pulvinar eros id, facilisis nisi. Proin ut blandit tortor, in tempor tellus. Sed lacus metus, hendrerit eu orci ac, aliquam commodo lacus.Morbi gravida pulvinar orci, et consectetur enim consectetur non. Proin nunc leo, tincidunt sed lacinia</p>
				<p>Fusce eu felis et sapien malesuada pretium a ac eros. Praesent quis hendrerit quam. Integer mollis est a cursus pulvinar. Proin leo neque, posuere eu metus </p>
				<a href="#" data-toggle="modal" data-target="#myModal">Read More</a>
			</div>
			<div class="clearfix">
			</div>
		</div>
	</div>
	<div class="feat-bottom">
		<h4>THE PURPOSE OF EDUCATION IS TO MAKE MINDS NOT CAREERS</h4>
	</div>
{% endblock %}
</body>

templates/libraniantemplates/libranianservice.html
{% extends 'libraniantemplates/libranianbase.html' %}
{% load static %}
<title>
	{% block title %}services{% endblock %}
</title>
<body>
{% block content %}
<div class="services" id="services">
		<div class="container">
			<h3>Our services</h3>
			<div class="col-md-4 services-grids services-grids1">
				<span class="glyphicon glyphicon-education" aria-hidden="true"></span>
				<h4>educate people</h4>
				<p>share our knowledge to all people </p>
			</div>
			<div class="col-md-4 services-grids services-grids2">
				<span class="glyphicon glyphicon-briefcase" aria-hidden="true"></span>
				<h4>keep records</h4>
				<p>keep all recoreds of all the people </p>
			</div>
			<div class="col-md-4 services-grids services-grids3">
				<span class="glyphicon glyphicon-book" aria-hidden="true"></span>
				<h4>provide output</h4>
				<p>provide different sorts of education to the people  </p>
			</div>
			<div class="clearfix"></div>
		</div>
	</div>
	<!-- Gallery -->
	<div class="gallery" id="gallery">
		<div class="container">
			<h3>GALLERY</h3>
			<div class="gallery-grids">
				<div class="col-md-6 col-sm-6 gallery-grids-left gallery-grids-left-gallery1-top">
					<div class="gallery-grid">
						<a class="example-image-link" href="{% static 'images/gallery-1.jpg' %}" data-lightbox="example-set" data-title="">
							<div class="grid">
								<figure class="effect-apollo">
									<img src="{% static 'images/gallery-1.jpg' %}" alt=""/>
										<figcaption></figcaption>
								</figure>
							</div>
						</a>
					</div>
					<div class="gallery-grids-left-sub">
						<div class="col-md-6 col-sm-6 gallery-grids-left-subl">
							<div class="gallery-grid">
								<a class="example-image-link" href="{% static 'images/gallery-4.jpg' %}" data-lightbox="example-set" data-title="">
									<div class="grid">
										<figure class="effect-apollo">
											<img src="{% static 'images/gallery-4.jpg' %}" alt=""/>
												<figcaption></figcaption>
										</figure>
									</div>
								</a>
							</div>
							<div class="gallery-grid gallery-grid-sub grid-middle gallery-grid-sub-left-bottom">
								<a class="example-image-link" href="{% static 'images/gallery-5.jpg' %}" data-lightbox="example-set" data-title="">
									<div class="grid">
										<figure class="effect-apollo">
											<img src="{% static 'images/gallery-5.jpg' %}" alt=""/>
												<figcaption></figcaption>
										</figure>
									</div>
								</a>
							</div>
						</div>
						<div class="col-md-6 col-sm-6 gallery-grids-left-subr gallery-grids-left-subr-long">
							<div class="gallery-grid">
								<a class="example-image-link" href="{% static 'images/gallery-7.jpg' %}" data-lightbox="example-set" data-title="">
									<div class="grid">
										<figure class="effect-apollo">
											<img src="{% static 'images/gallery-7.jpg' %}" alt=""/>
												<figcaption></figcaption>
										</figure>
									</div>
								</a>
							</div>
						</div>
						<div class="clearfix"></div>
					</div>
				</div>
				<div class="col-md-6 col-sm-6 gallery-grids-left">
					<div class="col-md-6 col-sm-6 gallery-grids-right gallery-grids-right-first">
						<div class="gallery-grid">
							<a class="example-image-link" href="{% static 'images/gallery-2.jpg' %}" data-lightbox="example-set" data-title="">
								<div class="grid">
									<figure class="effect-apollo">
										<img src="{% static 'images/gallery-2.jpg' %}" alt=""/>
											<figcaption></figcaption>
									</figure>
								</div>
							</a>
						</div>
					</div>
					<div class="col-md-6 col-sm-6 gallery-grids-right gallery-grids-right-two">
						<div class="gallery-grid">
							<a class="example-image-link" href="{% static 'images/gallery-3.jpg' %}" data-lightbox="example-set" data-title="">
								<div class="grid">
									<figure class="effect-apollo">
										<img src="{% static 'images/gallery-3.jpg' %}" alt=""/>
											<figcaption></figcaption>
									</figure>
								</div>
							</a>
						</div>
					</div>
					<div class="clearfix"></div>
					<div class="gallery-grids-right1 gallery-grids-right-hand">
						<div class="gallery-grid">
							<a class="example-image-link" href="{% static 'images/gallery-6.jpg' %}" data-lightbox="example-set" data-title="">
								<div class="grid">
									<figure class="effect-apollo">
										<img src="{% static 'images/gallery-6.jpg' %}" alt=""/>
											<figcaption></figcaption>
									</figure>
								</div>
							</a>
						</div>
					</div>
					<div class="col-md-6 col-sm-6 gallery-grids-right gallery-8">
						<div class="gallery-grid">
							<a class="example-image-link" href="{% static 'images/gallery-8.jpg' %}" data-lightbox="example-set" data-title="">
								<div class="grid">
									<figure class="effect-apollo">
										<img src="{% static 'images/gallery-8.jpg' %}" alt=""/>
											<figcaption></figcaption>
									</figure>
								</div>
							</a>
						</div>
					</div>
					<div class="col-md-6 col-sm-6 gallery-grids-right gallery-9">
						<div class="gallery-grid">
							<a class="example-image-link" href="{% static 'images/gallery-9.jpg' %}" data-lightbox="example-set" data-title="">
								<div class="grid">
									<figure class="effect-apollo">
										<img src="{% static 'images/gallery-9.jpg' %}" alt=""/>
											<figcaption></figcaption>
									</figure>
								</div>
							</a>
						</div>
					</div>
					<div class="clearfix"></div>
				</div>
				<div class="clearfix"></div>
			</div>

		</div>
	</div>
{% endblock %}	
</body>

templates/libraniantemplates/login.html
{% extends 'libraniantemplates/libranianbase.html' %}
{% load static %}
<title>{% block title %}login{% endblock %}</title>
{% block content %}
<div class="container">

  <div class="card container" style="width: 60rem;">
    <div class="card">
        <div class="card-header" style="background-color: yellow;text-align: center; padding: 20px;">
           Login
        </div>
        {% if error %}
          {{ error }}
        {% endif %}
        <br>
      <form method="post" action="#">
         {% csrf_token %}
          <!-- <div class="form-group">
            {{ form.as_p }}
          </div>
          <button>submit</button> -->
            <div class="form-group">
              <label>Username</label>
              <p>{{ form.username }}</p>

              <!-- <label>Username</label>
              <input type="username" class="form-control" id="username" aria-describedby="emailHelp" placeholder="Enter username" value="{{ username }}"> -->      
            </div>
            <div class="form-group">
              <label>password</label>

              {{ form.password }}
            </div>
            <div class="form-check">
              <input type="checkbox" class="form-check-input" id="exampleCheck1">
              <label class="form-check-label" for="exampleCheck1">Check me out</label>
            </div>
            <button type="submit" class="btn btn-primary">Submit</button>
      </form>
         
    </div>
  </div>
</div>
          

<br>
<br>
<br>
{% endblock %}