libraryapp/urls.py
from django.conf.urls import url
from .views import *
from django.urls import path
from . import views

app_name = 'libraryapp'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('about/', AboutView.as_view(), name='about'),
    path('services/', ServiceView.as_view(), name='service'),
    path('contact/', ContactView.as_view(), name='contact'),
    path('login/', LoginForm.as_view(), name='login'),
    path('admin/home/', AdminHome.as_view(), name='adminhome'),
    path('admin/book/list/', BookListView.as_view(), name='booklist'),
    path('admin/book/create/', BookCreateView.as_view(), name='bookcreate'),
    path('admin/book/update/<int:pk>/',
         BooKUpdateView.as_view(), name='bookupdate'),
    path('admin/book/delete/<int:pk>/',
         BookdeleteView.as_view(), name='bookdelete'),
    path('admin/student/list', StudentListView.as_view(), name='studentlist'),
    path('admin/student/create', StudentCreateView.as_view(), name='studentcreate'),
    path('admin/student/update<int:pk>', StudentUpdateView.as_view(), name='studentupdate'),
    path('admin/student/delete/<int:pk>/',
         StudentDeleteView.as_view(), name='studentdelete'),
    path('admin/student/issue/',views.IssueBookView,name = 'issue'),





]

libraryproject/urls.py
from django.conf.urls import url
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    path('', include('libraryapp.urls')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/admintemplates/adminbase.html
{% load static %}
<!DOCTYPE HTML>
<html>
<head>
<title>Modern an Admin Panel Category Flat Bootstarp Resposive Website Template | Home :: w3layouts</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="keywords" content="Modern Responsive web template, Bootstrap Web Templates, Flat Web Templates, Andriod Compatible web template, 
Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyErricsson, Motorola web design" />
<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
 <!-- Bootstrap Core CSS -->
<link href="{% static 'adminstatic/css/bootstrap.min.css' %}" rel='stylesheet' type='text/css' />

<!-- Custom CSS -->
<link href="{% static 'adminstatic/css/style.css' %}" rel='stylesheet' type='text/css' />
<!-- Graph CSS -->
<link href="{% static 'adminstatic/css/lines.css' %}" rel='stylesheet' type='text/css' />
<!-- <link href="{% static 'adminstatic/css/font-awesome.css' %}" rel="stylesheet">  -->
<link rel="stylesheet" type="text/css" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
<!-- jQuery -->
<script src="{% static 'adminstatic/js/jquery.min.js' %}"></script>
<!----webfonts--->
<link href='http://fonts.googleapis.com/css?family=Roboto:400,100,300,500,700,900' rel='stylesheet' type='text/css'>
<!---//webfonts--->  
<!-- Nav CSS -->
<link href="{% static 'adminstatic/css/custom.css' %}" rel="stylesheet">
<!-- Metis Menu Plugin JavaScript -->
<script src="{% static 'adminstatic/js/metisMenu.min.js' %}"></script>
<script src="{% static 'adminstatic/js/custom.js' %}"></script>
<!-- Graph JavaScript -->
<script src="{% static 'adminstatic/js/d3.v3.js' %}"></script>
<script src="{% static 'adminstatic/js/rickshaw.js' %}"></script>
</head>
<body>
<div id="wrapper">
     <!-- Navigation -->
        <nav class="top1 navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#">Mylibrary</a>
            </div>
            <!-- /.navbar-header -->
            <ul class="nav navbar-nav navbar-right">
				<li class="dropdown">
	        		<a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-expanded="false"><i class="fa fa-comments-o"></i><span class="badge">4</span></a>
	        		<ul class="dropdown-menu">
						<li class="dropdown-menu-header">
							<strong>Messages</strong>
							<div class="progress thin">
							  <div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="40" aria-valuemin="0" aria-valuemax="100" style="width: 40%">
							    <span class="sr-only">40% Complete (success)</span>
							  </div>
							</div>
						</li>
						<li class="avatar">
							<a href="#">
								<img src="{% static 'adminstatic/images/1.png' %}" alt=""/>
								<div>New message</div>
								<small>1 minute ago</small>
								<span class="label label-info">NEW</span>
							</a>
						</li>
						<li class="avatar">
							<a href="#">
								<img src="{% static 'adminstatic/images/2.png' %}" alt=""/>
								<div>New message</div>
								<small>1 minute ago</small>
								<span class="label label-info">NEW</span>
							</a>
						</li>
						<li class="avatar">
							<a href="#">
								<img src="{% static 'adminstatic/images/3.png' %}" alt=""/>
								<div>New message</div>
								<small>1 minute ago</small>
							</a>
						</li>
						<li class="avatar">
							<a href="#">
								<img src="{% static 'adminstatic/images/4.png' %}" alt=""/>
								<div>New message</div>
								<small>1 minute ago</small>
							</a>
						</li>
						<li class="avatar">
							<a href="#">
								<img src="{% static 'adminstatic/images/5.png' %}" alt=""/>
								<div>New message</div>
								<small>1 minute ago</small>
							</a>
						</li>
						<li class="avatar">
							<a href="#">
								<img src="{% static 'adminstatic/images/pic1.png' %}" alt=""/>
								<div>New message</div>
								<small>1 minute ago</small>
							</a>
						</li>
						<li class="dropdown-menu-footer text-center">
							<a href="#">View all messages</a>
						</li>	
	        		</ul>
	      		</li>
			    <li class="dropdown">
	        		<a href="#" class="dropdown-toggle avatar" data-toggle="dropdown"><img src="{% static 'adminstatic/images/1.png' %}"><span class="badge">9</span></a>
	        		<ul class="dropdown-menu">
						<li class="dropdown-menu-header text-center">
							<strong>Account</strong>
						</li>
						<li class="m_2"><a href="#"><i class="fa fa-bell-o"></i> Updates <span class="label label-info">42</span></a></li>
						<li class="m_2"><a href="#"><i class="fa fa-envelope-o"></i> Messages <span class="label label-success">42</span></a></li>
						<li class="m_2"><a href="#"><i class="fa fa-tasks"></i> Tasks <span class="label label-danger">42</span></a></li>
						<li><a href="#"><i class="fa fa-comments"></i> Comments <span class="label label-warning">42</span></a></li>
						<li class="dropdown-menu-header text-center">
							<strong>Settings</strong>
						</li>
						<li class="m_2"><a href="#"><i class="fa fa-user"></i> Profile</a></li>
						<li class="m_2"><a href="#"><i class="fa fa-wrench"></i> Settings</a></li>
						<li class="m_2"><a href="#"><i class="fa fa-usd"></i> Payments <span class="label label-default">42</span></a></li>
						<li class="m_2"><a href="#"><i class="fa fa-file"></i> Projects <span class="label label-primary">42</span></a></li>
						<li class="divider"></li>
						<li class="m_2"><a href="#"><i class="fa fa-shield"></i> Lock Profile</a></li>
						<li class="m_2"><a href="#"><i class="fa fa-lock"></i> Logout</a></li>	
	        		</ul>
	      		</li>
			</ul>
			<form class="navbar-form navbar-right">
              <input type="text" class="form-control" value="Search..." onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'Search...';}">
            </form>
            <div class="navbar-default sidebar" role="navigation">
                <div class="sidebar-nav navbar-collapse">
                    <ul class="nav" id="side-menu">
                        <li>
                            <a href="index.html"><i class="fa fa-dashboard fa-fw nav_icon"></i>Dashboard</a>
                        </li>
                        <li>
                            <a href="{% url 'libraryapp:booklist' %}"><i class="fa fa-book nav_icon"></i>Book<span class="fa arrow"></span></a>
                            <!-- /.nav-second-level -->
                        </li>
                        <li>
                            <a href="{% url 'libraryapp:studentlist' %}"><i class="fa fa-users nav_icon"></i>Student<span class="fa arrow"></span></a>
                            <!-- /.nav-second-level -->
                        </li>

                        <li>
                            <a href="widgets.html"><i class="fa fa-flask nav_icon"></i>Widgets</a>
                        </li>
                         <li>
                            <a href="#"><i class="fa fa-list-alt nav_icon"></i>Issue</a>
                        </li>
                        <li>
                            <a href="#"><i class="fa fa-list-alt nav_icon"></i>Return</a>
                        </li>
                        <li>
                            <!-- <a href="#"><i class="fa fa-sitemap fa-fw nav_icon"></i>Css<span class="fa arrow"></span></a> -->
                            <ul class="nav nav-second-level">
                                <li>
                                    <a href="media.html">Media</a>
                                </li>
                                <li>
                                    <a href="login.html">Login</a>
                                </li>
                            </ul>

                            <!-- /.nav-second-level -->
                        </li>
                    </ul>
                </div>
                <!-- /.sidebar-collapse -->
            </div>
            <!-- /.navbar-static-side -->
        </nav>

        {% block banner %}{% endblock %}
         <div id="page-wrapper">
        <div class="graphs">

        {% block content %}
        {% endblock %}

		<div class="copy">
            <p>Copyright &copy; 2015 Modern. All Rights Reserved | Design by <a href="http://w3layouts.com/" target="_blank">Viper</a> </p>
	    </div>
		</div>
       </div>
      <!-- /#page-wrapper -->
   </div>
    <!-- /#wrapper -->
    <!-- Bootstrap Core JavaScript -->
    <script src="{% static 'adminstatic/js/bootstrap.min.js' %}"></script>
</body>
</html>

templates/admintemplates/adminbookcreate.html
{% extends 'admintemplates/adminbase.html' %}
{% load static %}
{% block content %}
<div class="container">
	
	<div class="row col-1 container">
		<div class="col-md-12">
			<h4>Add Book</h4>
			<form method="post" enctype="multipart/form-data">
				{% csrf_token %}
				

				{{form.as_p}}
				<button class="btn btn-primary">submit</button>

				


			</form>
				
		</div>
		<br>


	</div>
</div>

{% endblock %}

templates/admintemplates/adminbookdelete.html
{% extends 'admintemplates/adminbase.html' %}
{% load static %}
{% block content %}
<div class="row col-1">
	<div class="col-md-12">
		<h2>book delete</h2>
		<form method="post">
			{% csrf_token %}
			<h4>Do you want to delete this book?</h4>
			<button class="btn btn-danger">Delete</button>



			

		</form>
			

		

	</div>
	


</div>
<br>
{% endblock %}

templates/admintemplates/adminbooklist.html
{% extends 'admintemplates/adminbase.html' %}
{% load static %}
{% block content %}
	<div class="row">
		<div class="col-md-12 table-responsive-sm">
			<h3>Book list</h3>
			<a href="{% url 'libraryapp:bookcreate' %}" class="btn btn-info"><i class="fa fa-plus"></i></a>
			
			<table class=" table table-bordered ">
				<thead style="background-color: yellow;color:black;">
					<tr class="text-dark">
						<th>S.N</th>
						<th>title</th>
						<th>barcode</th>
						<th>image</th>
						<th>category</th>
						<th>publisher</th>
						<th>author</th>
						<th>action</th>
				
					</tr>	

				</thead>
				<tbody>
					{% for book in booklists %}
					<tr style="color: black;">
						<td>{{forloop.counter}}</td>
						<td>{{book.title}}</td>
						<td>{{book.barcode}}</td>
						<td><img src="{{book.image.url}}" width="75"></td>
						<td>{{book.category}}</td>
						

						<td>{{book.publisher}}</td>
						<td>{{book.author}}</td>
						<td>
							<a href="{% url 'libraryapp:bookupdate' book.id %}" class="btn btn-success"><i class="fa fa-pencil"></i></a>
							<a href="{% url 'libraryapp:bookdelete' book.id %}" class="btn btn-warning"><i class="fa fa-trash"></i></a>

						</td>


						<td>
							
						</td>
					</tr>	


					{% endfor %}
				</tbody>
					
			</table>
		</div>
	</div>
{% endblock %}

templates/admintemplates/adminhome.html
{% extends 'admintemplates/adminbase.html' %}
{% load static %}
{% block content %}

{% endblock %}

templates/admintemplates/adminstudentcreate.html
{% extends 'admintemplates/adminbase.html' %}
{% load static %}
 <title>{% block title %}add_student{% endblock %}</title>
{% block content %}
<div class="container">
  <div class="card-body">
      <div class="container">
         <div class="row">

              <div class="container">

                <form method="POST" class="form-horizontal" enctype="multipart/form-data" action="#">
                    <h1 style="background-color:green;color:black">Student registration</h1>
                            {% csrf_token %}
                      <div class="text-body">
                          {{ form.as_p }}

                          <br>
                            <input type="submit" value="save"class="btn btn-info" style="background-color:blue"/>
                      </div>
                </form>

              </div>
         </div>
      </div>
  </div>
</div>
{% endblock %}

templates/admintemplates/adminstudentlist.html
{% extends 'admintemplates/adminbase.html' %}
{% load static %}
{% block content %}
	<div class="row">
		<div class="col-md-12 table-responsive-sm">
			<h3>Book list</h3>
			<a href="{% url 'libraryapp:studentcreate' %}" class="btn btn-info"><i class="#"></i>Add</a>
			
			<table class=" table table-bordered ">
				<thead style="background-color:#000080;color:black;">
					<tr class="text-dark">
						<th>S.N</th>
						<th>name</th>
						<th>program</th>
						<th>image</th>
						<th>semester</th>
						<th>section</th>
						<th>action</th>
				
					</tr>	

				</thead>
				<tbody>
					{% for student in studentlists %}
					<tr class="text-secondary">
						<td>{{forloop.counter}}</td>
						<td>{{student.name}}</td>
						<td>{{student.program}}</td>
						<td><img src="{{student.image.url}}" width="75"></td>
						<td>{{student.semester}}</td>
						<td>{{student.section}}</td>				
						<td>
							<a href="{% url 'libraryapp:studentupdate' student.id %}" class="btn btn-warning"><i></i>Edit</a>
							<a href="{% url 'libraryapp:studentdelete' student.id %}" class="btn btn-success"><i></i>Remove</a>

						</td>
					</tr>	


					{% endfor %}
				</tbody>
					
			</table>
		</div>
	</div>
{% endblock %}

templates/admintemplates/issuebook.html
{% extends 'admintemplates/adminbase.html' %}
 <title>{% block title %}borrow{% endblock %}</title>
{% block content %}
   <div>
        <div class="alert alert-info">Transaction / Borrowing</div>
        <form method="POST" action="">
            {% csrf_token %}
            <div class="form-group pull-left">
                <label>Student Name:</label>
                <br/>
                <select class="form-control" name="student_id" id="student">
                    {% for student in students %}
                        <option value='{{ student.id }}'>{{ student.name }}</option>
                    {% endfor %}
                </select>
            </div>
            <div class="form-group pull-right">
                <button name="save_borrow" class="btn btn-primary"><span class="glyphicon glyphicon-thumbs-up"></span>
                    Borrow
                </button>
            </div>
            <table id="table" class="table table-stripped">
                <thead class="alert-success">
                <tr>
                    <th>Select</th>
                    <th>Book Title</th>
                    <th> Book_barcode</th>
                    <th>publisher</th>
                    <th>Available</th>
                    <th>Left</th>
                </tr>
                </thead>
                <tbody>
                {% for book, data in datas %}
                    <tr>
                        <td>
                            {% if data == -1 %}
                                <label class='text-danger'>Not Available</label>
                            {% else %}
                                <input type="hidden" name="book_id" value="{{ book.id }}">
                                <input type="checkbox" name="selector" value="{{ book.id }}">
                            {% endif %}
                        </td>
                        <td>{{ book.title }}</td>
                        <td>{{ book.book_type }}</td>
                        <td>{{ book.author }}</td>
                        <td>{{ book.available }}</td>
                        <td>
                            {% if data == -1 %}
                                <center><label class='text-danger'>Not Available</label></center>
                            {% else %}
                                {{ data }}
                            {% endif %}
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </form>
    </div>

{% endblock %}

templates/admintemplates/studentdelete.html
{% extends 'admintemplates/adminbase.html' %}
{% load static %}
{% block content %}
<div class="row col-1">
	<div class="col-md-12">
		<h2>student delete</h2>
		<form method="post">
			{% csrf_token %}
			<h4>Do you want to delete this student?</h4>
			<button class="btn btn-danger">Delete</button>



			

		</form>
			

		

	</div>
	


</div>
<br>
{% endblock %}